### ISSUE TITLE
Not working with K2 2.8

### ISSUE THREAD

**Issue by blueforce** [kmgalanakis/Inceptive-Multiple-Categories-for-K2#6] opened 2017-09-27 10:53 UTC
Hi the plugin produces a blank page after saving the item.
If I turn the error Reporting to maximum so I get this message:

Fatal error: Cannot declare class upload, because the name is already in use in /ROOT/administrator/components/com_k2/lib/class.upload.php on line 624

Do you have any solution for that?

**Comment by kmgalanakis** [comment] 2017-09-30 07:19
Hello.

Unfortunately, I cannot reproduce the issue locally. Do you mind letting me know more about your setup?

What other plugins do you have installed? 

Mind you that our plugin is not using the `upload` class.

**Comment by blueforce** [comment] 2017-09-30 07:26
My setup is:

- Joomla 3.8.0
- K2 V2.8.0
- Multiple-Categories-for-K2 V1.3
- PHP 7.0.22

Thank you in advance...

**Comment by kmgalanakis** [comment] 2017-09-30 07:39
I use the exact same setup and I cannot reproduce the issue. 

Could you please disable all the other plugin and leave only K2 and Multiple-Categories-for-K2 activated to see if the issue still occurs?

Thank

**Comment by blueforce** [comment] 2017-09-30 10:51
curious I have no clou. I've currently installed only K2 core componentes
but I still using overrides... and thats aspects only FE-Elements. hmmm

**Comment by kmgalanakis** [comment] 2017-09-30 14:16
Sorry, I'm not following.

**Comment by blueforce** [comment] 2017-09-30 14:22
thank you, you can close this issue

**Comment by kmgalanakis** [comment] 2017-09-30 14:27
I'm closing this.

**Closed as completed by kmgalanakis** 2017-09-30 14:27 UTC
